image: Visual Studio 2017

platform:
  - x64
  - x86

configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS%

build_script:
  - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
  - '%CONFIGURATION%\robust_iterator_test.exe'
