configuration:
  - Debug
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 14 2015
      VS_PLATFORM: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 14 2015
      VS_PLATFORM: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15 2017
      VS_PLATFORM: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15 2017
      VS_PLATFORM: x64

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio %VS_VERSION%" -A %VS_PLATFORM%

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - '%CONFIGURATION%\robust_iterator_test.exe'
