language: cpp
sudo: required

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - ./robust_iterator_test
